INSERT INTO SHOP_ITEM(ID, NAME, AMOUNT, IS_BOUGHT) VALUES (1, 'bread', 2, false);
INSERT INTO SHOP_ITEM(ID, NAME, AMOUNT, IS_BOUGHT) VALUES (2, 'egg', 10, false);
INSERT INTO SHOP_ITEM(ID, NAME, AMOUNT, IS_BOUGHT) VALUES (3, 'milk', 1, true);
